name: flutter_dmx
description: "A simple and flexible DMX control plugin for Flutter"
version: 1.0.0
repository: https://github.com/CodeSleeker/flutter-dmx

environment:
  sdk: ^3.8.1
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

  #https://pub.dev/packages/freezed_annotation
  freezed_annotation: ^3.1.0

  #https://pub.dev/packages/mocktail
  mocktail: ^1.0.4

  #https://pub.dev/packages/json_annotation
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  #https://pub.dev/packages/build_runner
  build_runner: ^2.5.4

  #https://pub.dev/packages/json_serializable
  json_serializable: ^6.9.5

  #https://pub.dev/packages/freezed
  freezed: ^3.1.0
  
flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_dmx
        pluginClass: FlutterDmxPlugin
      ios:
        pluginClass: FlutterDmxPlugin
      linux:
        pluginClass: FlutterDmxPlugin
      macos:
        pluginClass: FlutterDmxPlugin
      windows:
        pluginClass: FlutterDmxPluginCApi
